.TH OPENWIPS-NG 1 "JANUARY 2012" "Version 0.1 BETA"

.SH NAME
openwips-ng - a 802.11 Wireless Intrusion Prevention System

.SH DESCRIPTION
.BI openwips-ng
detects attacks and prevents unauthorized access on a 802.11 network.

The system is composed of three parts: the
.B openwips-ng-sensor(1),
the
.B openwips-ng-server(1)
and the interface.

The
.B openwips-ng-sensor(1)
is where all the raw packets are captured, stripped and sent over a secure channel to the
.B openwips-ng-server(1).
It may also respond to attacks when ordered to by the
.B openwips-ng-server(1).
The
.B openwips-ng-server(1)
handle the analysis process, threat detection, logging and threat management. The interface is the GUI allowing the user to easily manage all the modules and settings related to the
.B openwips-ng-sensor(1)
and
.B openwips-ng-server(1).

.SH AUTHOR
This manual page was written by Steve Cloutier <scloutier@openwips-ng.org>.
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation
.SH SEE ALSO
.br
.B openwips-ng-sensor(1)
.br
.B openwips-ng-server(1)